apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    name: kafka-pod
    app: kafka-cluster
spec:
  containers:
    - name: kafka
      image: confluentinc/cp-kafka:latest
      ports:
        - containerPort: 9092