apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deploy
  labels:
    name: kafka-deploy
    app: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-deploy
      app: kafka-cluster
  template:
    metadata:
      name: kafka-pod
      labels:
        name: kafka-pod
        app: kafka-cluster
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper_confluent:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka_confluent:9092,PLAINTEXT_HOST://localhost:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"

