apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-pod
  labels:
    name: zookeeper-pod
    app: kafka-cluster
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:latest
      ports:
        - containerPort: 2181